// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmineolacdftrviwytws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaW5lb2xhY2RmdHJ2aXd5dHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTQ3NjAsImV4cCI6MjA3MDczMDc2MH0.T9m-LQcbBJmL4KY8ecOHwzfU-mlwpnDKXTrCDzjMog8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});